### ISSUE TITLE
How to use v2.37 with single end reads?

### ISSUE THREAD

**Issue by JX-Zhong** [xinehc/args_oap#1]
Hi 
   I'm trying to use ARGs_OAP with my single end reads, but it still reminds me that R1 R2 file was necessary for performing. But I saw the newest version was able to treat single end reads.

**Comment by xinehc** [comment]
The current version of args_oap does not support single-end reads, we hope to remove this constraint in future updates. 

As a workaround, you could generate some fake R2 files (empty *_2.fa) to make args_oap running.

Hope this helps,
Xi
