### ISSUE TITLE
KO30_DIAMOND.dmnd out of date

### ISSUE THREAD

**Issue by suskraem** [xinehc/args_oap#2]
Hello, 
I'm encountering an issue with the KO30 database when running args-oap. I'm using diamond version 0.9.32. The SARG.dmnd file works, but the KO30.dmnd file yields the following error:
Error: Database was built with an older version of Diamond and is incompatible.
 I would like to rebuild it with my version of diamond, but don't have the .fasta file available. Could you maybe post it?

Thanks a lot,
Susanne

**Comment by xinehc** [comment]
We added the KO30 fasta file in a recent update. See [all_KO30.fasta](https://github.com/xinehc/args_oap/blob/ae559a52e9c7e55c5cc3b3045d174e91f838ec4e/args_oap/DB/all_KO30.fasta).

HTH, Xi
