### ISSUE TITLE
Input file as contig.fasta

### ISSUE THREAD

**Issue by pratibha-kadam** [xinehc/args_oap#34]
Hello There,
I am working on ARG detection from wastewater samples.
I have made contig.fasta so can I use that here as a single input file??

Also, I am mainly focusing on 5 Drugs (Carbapenem, Azithromycin, Methicilin, Bedaquiline, fluoroquinolone) 

When I checked for bedaquiline resistance gene I suppose there are no BDQ resistance gene are present in the SARG v3.2.1-F database.

Please provide information on these drugs resistance genes wheather its there are not.

Many Thanks in Advance and I appreciate your Tool

**Comment by xinehc** [comment]
Hi,

args_oap is not designed for contigs so you will not get a reasonable result if you use contigs as input. You may consider first predicting ORFs then directly map them to the sarg database using e.g. blast.

Regarding the BDQ resistance gene, if you don't find it by key words then it is likely not present in the sarg database.
